# Generated by Django 5.0.7 on 2024-08-10 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='question_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
