# Generated by Django 5.0.7 on 2024-08-10 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_questions_question_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='question_number',
            field=models.PositiveIntegerField(),
        ),
    ]
