# Generated by Django 5.0.7 on 2024-08-10 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_alter_questions_question_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='question_number',
        ),
        migrations.AddField(
            model_name='categories',
            name='category_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questions',
            name='question_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
