# Generated by Django 5.0.7 on 2024-08-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0004_remove_questions_question_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='question_order',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
