# Generated by Django 5.0.7 on 2024-08-11 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0005_alter_questions_question_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='question_order',
            field=models.IntegerField(unique=True),
        ),
    ]
