# Generated by Django 5.0.7 on 2024-08-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0006_alter_questions_question_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='category_order',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question_order',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
