# Generated by Django 4.2.14 on 2024-08-11 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0007_alter_categories_category_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='question_order',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='questions',
            unique_together={('question_fk', 'question_order')},
        ),
    ]
