# Generated by Django 5.0.7 on 2024-08-15 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0008_alter_questions_question_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='heading',
            field=models.CharField(default='Default Heading', max_length=100),
        ),
        migrations.AddField(
            model_name='categories',
            name='photo',
            field=models.ImageField(blank=True, default='assessment/static/assessment/questions.jpg', upload_to='Contributors/'),
        ),
        migrations.CreateModel(
            name='Paragraphs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph', models.CharField(max_length=100)),
                ('paragraph_order', models.PositiveIntegerField()),
                ('paragraph_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.categories')),
            ],
            options={
                'unique_together': {('paragraph_fk', 'paragraph_order')},
            },
        ),
    ]
