# Generated by Django 5.0.7 on 2024-08-15 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0009_categories_heading_categories_photo_paragraphs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='photo',
            field=models.ImageField(blank=True, upload_to='Contributors/'),
        ),
    ]
