# Generated by Django 5.0.7 on 2024-08-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0010_alter_categories_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paragraphs',
            name='paragraph',
            field=models.TextField(),
        ),
    ]
