# Generated by Django 5.0.7 on 2024-08-15 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0011_alter_paragraphs_paragraph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='photo',
            field=models.ImageField(blank=True, upload_to='l3nFsEdq2g/'),
        ),
    ]
