# Generated by Django 5.0.7 on 2024-08-22 11:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0016_alter_categories_photo_useranswer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserAnswer',
            new_name='UserAnswers',
        ),
        migrations.RenameField(
            model_name='useranswers',
            old_name='answer',
            new_name='answer_fk',
        ),
        migrations.RenameField(
            model_name='useranswers',
            old_name='question',
            new_name='question_fk',
        ),
        migrations.RenameField(
            model_name='useranswers',
            old_name='user',
            new_name='user_fk',
        ),
        migrations.AlterField(
            model_name='categories',
            name='photo',
            field=models.ImageField(blank=True, upload_to='7KNHzVGUN4/'),
        ),
        migrations.AlterUniqueTogether(
            name='useranswers',
            unique_together={('user_fk', 'question_fk', 'answer_fk')},
        ),
    ]
