# Generated by Django 5.0.7 on 2024-08-29 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0017_rename_useranswer_useranswers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='photo',
            field=models.ImageField(blank=True, upload_to='b5GF5YbcVn/'),
        ),
    ]
