# Generated by Django 5.0.7 on 2024-08-29 07:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0018_alter_categories_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='useranswers',
            old_name='answer_fk',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='useranswers',
            old_name='question_fk',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='useranswers',
            old_name='user_fk',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='categories',
            name='photo',
            field=models.ImageField(blank=True, upload_to='zSeeKnnUvg/'),
        ),
        migrations.AlterUniqueTogether(
            name='useranswers',
            unique_together={('user', 'question', 'answer')},
        ),
    ]
