# Generated by Django 5.0.7 on 2024-08-29 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0019_rename_answer_fk_useranswers_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='photo',
            field=models.ImageField(blank=True, upload_to='1sD5g2lZK7/'),
        ),
    ]
