# Generated by Django 5.0.7 on 2024-08-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0022_alter_categories_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='photo',
            field=models.ImageField(blank=True, upload_to='8OtDRSDYYg/'),
        ),
    ]
