# Generated by Django 4.2.14 on 2024-08-30 12:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assessment', '0023_alter_categories_photo_usercategories'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usercategories',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='usercategories',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='categories',
            name='photo',
            field=models.ImageField(blank=True, upload_to='TnHIrttK8S/'),
        ),
        migrations.AlterUniqueTogether(
            name='usercategories',
            unique_together={('user', 'category', 'score')},
        ),
    ]
