# Generated by Django 5.0.7 on 2024-09-09 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0023_alter_categories_photo'),
        ('assessment', '0024_alter_usercategories_unique_together_and_more'),
    ]

    operations = [
    ]
