# Generated by Django 4.2.14 on 2024-09-18 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0025_merge_20240909_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='photo',
            field=models.ImageField(blank=True, upload_to='T7KqSkNrp0/'),
        ),
    ]
