# Generated by Django 4.2.14 on 2024-09-26 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assessment', '0026_alter_categories_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='photo',
            field=models.ImageField(blank=True, upload_to='tJGo6j2Jxu/'),
        ),
        migrations.CreateModel(
            name='UserResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radarChart', models.CharField(max_length=100)),
                ('barChart', models.CharField(max_length=100)),
                ('QuestionLock', models.BooleanField(default=False)),
                ('Change', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
