# Generated by Django 4.2.14 on 2024-10-04 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0028_alter_categories_photo_resultpageparaghraphs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='photo',
            field=models.ImageField(blank=True, upload_to='t4qyyVaVDF/'),
        ),
    ]
