# Generated by Django 4.2.14 on 2024-10-11 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0029_alter_categories_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='task',
            field=models.TextField(default='This is a deafult task for this question.'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='photo',
            field=models.ImageField(blank=True, upload_to='VWs0SlZRVx/'),
        ),
    ]
