# Generated by Django 4.2.14 on 2024-10-11 00:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assessment', '0030_questions_task_alter_categories_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='photo',
            field=models.ImageField(blank=True, upload_to='10cFWaZoZo/'),
        ),
        migrations.AlterUniqueTogether(
            name='useranswers',
            unique_together={('user', 'question')},
        ),
    ]
