# Generated by Django 4.2.14 on 2024-10-11 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0031_alter_categories_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='photo',
            field=models.ImageField(blank=True, upload_to='ZQL8sfeSBW/'),
        ),
    ]
