# Generated by Django 4.2.14 on 2024-10-11 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0034_questions_date_alter_categories_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswers',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='photo',
            field=models.ImageField(blank=True, upload_to='fAIR7WYZHp/'),
        ),
    ]
