# Generated by Django 4.2.14 on 2024-10-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0035_useranswers_date_alter_categories_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='photo',
            field=models.ImageField(blank=True, upload_to='lHKFUoXExH/'),
        ),
    ]
