# Generated by Django 4.2.14 on 2024-10-11 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0036_alter_categories_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useranswers',
            old_name='date',
            new_name='mdate',
        ),
        migrations.AlterField(
            model_name='categories',
            name='photo',
            field=models.ImageField(blank=True, upload_to='XkpzIYKGIv/'),
        ),
    ]
