# Generated by Django 5.0.7 on 2024-10-17 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0037_rename_date_useranswers_mdate_alter_categories_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='photo',
            field=models.ImageField(blank=True, upload_to='D8HUjgxxn9/'),
        ),
    ]
