# Generated by Django 4.2.16 on 2024-11-21 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0039_alter_categories_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='photo',
            field=models.ImageField(blank=True, upload_to='zrhpyX3myJ/'),
        ),
    ]
